function A=euler(PHI,theta,phi)
  A=[cos(phi)*cos(PHI)-sin(phi)*cos(theta)*sin(PHI),...
     -cos(phi)*cos(theta)*sin(PHI)-sin(phi)*cos(PHI),...
     sin(theta)*sin(PHI);
     cos(phi)*sin(PHI)+sin(phi)*cos(theta)*cos(PHI),...
     cos(phi)*cos(theta)*cos(PHI)-sin(phi)*sin(PHI),...
     -sin(theta)*cos(PHI);
     sin(phi)*sin(theta),...
     cos(phi)*sin(theta),...
     cos(theta)];
